import type { Product, Category } from '@/types';

export const categories: Category[] = [
  { id: '1', name: 'Одежда', slug: 'clothing', image_url: '/images/cat-clothing.jpg', sort_order: 1 },
  { id: '2', name: 'Аксессуары', slug: 'accessories', image_url: '/images/cat-accessories.jpg', sort_order: 2 },
  { id: '3', name: 'Сумки', slug: 'bags', image_url: '/images/cat-bags.jpg', sort_order: 3 },
  { id: '4', name: 'Головные уборы', slug: 'headwear', image_url: '/images/cat-headwear.jpg', sort_order: 4 },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Худи Cyberpunk V2',
    slug: 'hoodie-cyberpunk-v2',
    description: 'Оверсайз крой, дышащая техно-сетка. Разработано для цифровых кочевников.',
    price: 120,
    category_id: '1',
    images: ['/images/hoodie-1.jpg', '/images/hoodie-2.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Space Black', hex: '#171717' }, { name: 'Graphite', hex: '#404040' }, { name: 'Volt', hex: '#e9ffb9' }],
    material: '100% Хлопок',
    fit: 'Oversize',
    is_new: true,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-01-01',
  },
  {
    id: '2',
    name: 'Лонгслив Ghost Knit',
    slug: 'longsleeve-ghost-knit',
    description: 'Минималистичный лонгслив из мягкого трикотажа с едва заметной текстурой.',
    price: 65,
    category_id: '1',
    images: ['/images/longsleeve-1.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Phantom', hex: '#2a2a2a' }],
    material: '95% Хлопок, 5% Эластан',
    fit: 'Regular',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 30,
    created_at: '2024-01-05',
  },
  {
    id: '3',
    name: 'Брюки Карго Orbit',
    slug: 'cargo-orbit',
    description: 'Функциональные карго с множеством карманов и утягивающими манжетами.',
    price: 95,
    category_id: '1',
    images: ['/images/cargo-1.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Olive', hex: '#556B2F' }, { name: 'Black', hex: '#171717' }],
    material: '100% Нейлон',
    fit: 'Relaxed',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 25,
    created_at: '2024-01-10',
  },
  {
    id: '4',
    name: 'Футболка Velocity Graphic',
    slug: 'tshirt-velocity-graphic',
    description: 'Плотный органический хлопок 300GSM с высококачественным принтом и светоотражающими деталями.',
    price: 45,
    category_id: '1',
    images: ['/images/tshirt-1.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#171717' }, { name: 'White', hex: '#f5f5f5' }],
    material: 'Органический хлопок 300GSM',
    fit: 'Regular',
    is_new: false,
    is_limited: true,
    is_bestseller: false,
    stock: 15,
    created_at: '2024-01-15',
  },
  {
    id: '5',
    name: 'Бомбер Neon',
    slug: 'bomber-neon',
    description: 'Лёгкий бомбер с неоновыми акцентами и подкладкой из сетки.',
    price: 150,
    category_id: '1',
    images: ['/images/bomber-1.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Military', hex: '#4a5d23' }],
    material: '100% Полиэстер',
    fit: 'Regular',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 20,
    created_at: '2024-01-20',
  },
  {
    id: '6',
    name: 'Кепка Logo Distressed',
    slug: 'cap-logo-distressed',
    description: 'Состаренная кепка с вышитым логотипом Click.',
    price: 35,
    category_id: '4',
    images: ['/images/cap-1.jpg'],
    sizes: ['One Size'],
    colors: [{ name: 'Navy', hex: '#1a1a4e' }],
    material: '100% Хлопок',
    fit: 'Adjustable',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 40,
    created_at: '2024-01-25',
  },
  {
    id: '7',
    name: 'Click Signature Tee',
    slug: 'click-signature-tee',
    description: 'Оверсайз футболка из плотного хлопка с фирменным принтом.',
    price: 550000,
    category_id: '1',
    images: ['/images/sig-tee-1.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#171717' }],
    material: 'Плотный хлопок',
    fit: 'Oversize',
    is_new: true,
    is_limited: true,
    is_bestseller: false,
    stock: 10,
    created_at: '2024-02-01',
  },
  {
    id: '8',
    name: 'Utility Tech Tote',
    slug: 'utility-tech-tote',
    description: 'Водостойкая сумка с рефлективными деталями.',
    price: 790000,
    category_id: '3',
    images: ['/images/tote-1.jpg'],
    sizes: ['One Size'],
    colors: [{ name: 'Black', hex: '#171717' }],
    material: 'Водостойкий нейлон',
    fit: 'One Size',
    is_new: true,
    is_limited: false,
    is_bestseller: false,
    stock: 20,
    created_at: '2024-02-05',
  },
  {
    id: '9',
    name: 'Vortex Tech Худи 01',
    slug: 'vortex-tech-hoodie',
    description: 'Разработано для цифровых кочевников. Высоковольтные акценты и структурированный силуэт.',
    price: 129,
    category_id: '1',
    images: ['/images/vortex-1.jpg', '/images/vortex-2.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Space Black', hex: '#171717' }, { name: 'Graphite', hex: '#404040' }, { name: 'Volt', hex: '#e9ffb9' }],
    material: '100% Хлопок',
    fit: 'Oversize',
    is_new: true,
    is_limited: true,
    is_bestseller: true,
    stock: 8,
    created_at: '2024-02-10',
  },
  {
    id: '10',
    name: 'Cyber Windbreaker',
    slug: 'cyber-windbreaker',
    description: 'Ультимативная броня для городских джунглей.',
    price: 180,
    category_id: '1',
    images: ['/images/windbreaker-1.jpg'],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [{ name: 'Black', hex: '#171717' }],
    material: 'Ripstop Nylon',
    fit: 'Regular',
    is_new: false,
    is_limited: false,
    is_bestseller: true,
    stock: 15,
    created_at: '2024-02-15',
  },
];
