import type { Product, Category } from '@/types';

export const categories: Category[] = [
  { id: 'click-travel', name: 'Click Travel', slug: 'click-travel', image_url: '/images/categories/bags.svg', sort_order: 1 },
  { id: 'yashil-meros', name: 'Yashil Meros', slug: 'yashil-meros', image_url: '/images/categories/clothing.svg', sort_order: 2 },
  { id: 'kollaboratsii', name: 'Коллаборации', slug: 'kollaboratsii', image_url: '/images/categories/accessories.svg', sort_order: 3 },
  { id: 'golovnye-ubory', name: 'Головные уборы', slug: 'golovnye-ubory', image_url: '/images/categories/headwear.svg', sort_order: 4 },
  { id: 'aksessuary', name: 'Аксессуары', slug: 'aksessuary', image_url: '/images/categories/accessories.svg', sort_order: 5 },
];

export const products: Product[] = [
  {
    id: '107b4547-d576-4b05-9b7c-87fc6ebcd80c',
    name: 'Худи «Облако жадности»',
    slug: 'khudi-oblako-zhadnosti',
    description: 'Цвет: Светло-серый. Коллекция: Воздух, в котором мы дышим. Когда воздух превращают в валюту — теряется сама ценность жизни. Принт с черным облаком и национальными орнаментами в виде знаков валют — метафора того, как жадность и безразличие ведут к экологическим катастрофам. Маленькая фигура человека внизу — мы с вами, перед лицом разрушений. Принт от Kuznetsovs Gallery. Унисекс фасон. Натуральный дышащий хлопок. QR-код сзади ведёт к экологической инициативе Yashil Meros. Эта худи — как предупреждение. Кто мы, если нам нечем дышать?',
    price: 670000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/3a4c29ba-cf0f-47ed-9749-b6be30d18c2e.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/1cb305b6-b8c7-4ae9-8efc-67150c7ab285.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: 'Хлопок',
    fit: 'Unisex',
    is_new: true,
    is_limited: true,
    is_bestseller: true,
    stock: 50,
    created_at: '2024-06-01',
  },
  {
    id: 'dc0219b5-b2cf-4baf-9e88-8a894bbed5de',
    name: 'Кошелёк «Карты Деньги 2 Ключа»',
    slug: 'koshelyok-karty-dengi-2-klyucha',
    description: 'Минималистичный кожаный кошелёк для повседневной жизни — когда с собой нужно только самое важное. Карты Деньги 2 Ключа — это компактный кардхолдер, изготовленный вручную мастером в локальной мастерской. Каждое изделие создаётся из одной цельной детали натуральной кожи, аккуратно складывается в продуманную форму и фиксируется металлическими кнопками. Внутри: банковские и визитные карты, сложенные купюры, два ключа, не царапающие содержимое. Кожа со временем красиво стареет, приобретая индивидуальный характер — как и вещи, сделанные не на потоке, а с вниманием и заботой.',
    price: 285000,
    category_id: 'aksessuary',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/e22a341d-8409-4a13-b2b7-6612bcde2231.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/95d71cd4-dec0-4bd1-9a09-ca7bab8e0428.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Натуральная кожа',
    fit: '',
    is_new: true,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-02',
  },
  {
    id: 'e37b12d5-f73f-4257-a517-09bd1b34c92e',
    name: 'Косынка "Дождевик"',
    slug: 'kosynka-dozhdevik',
    description: 'Прозрачная косынка — это стильный и практичный аксессуар для защиты волос от дождя и ветра. Легкий влагостойкий материал сохраняет укладку, не скрывая ее, а аккуратная окантовка придает образу современный акцент. Удобные завязки позволяют отрегулировать посадку, обеспечивая комфорт в течение дня. Косынка аккуратно закрывает волосы по всей длине и подходит как к повседневной одежде, так и к более элегантным образам. Универсальный аксессуар на любую погоду — просто и со вкусом.',
    price: 80000,
    category_id: 'golovnye-ubory',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/def4cfe8-5450-4aa8-a814-0b41dc098260.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/b39a7eef-1f46-475b-891f-eb0e3e35f1a0.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/50fe5d22-b56b-4001-9956-433a088fdb0a.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Влагостойкий материал',
    fit: '',
    is_new: true,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-03',
  },
  {
    id: '2d2788ef-0da1-46ff-9fad-16177281b001',
    name: 'Футболка "Рост"',
    slug: 'futbolka-rost',
    description: 'Рост. Футболка о действии. Когда один шаг повторяется — он становится движением. Яркий зелёный — энергия роста и перемен. Принт — про силу, которая появляется, когда мы действуем вместе. Послание: Рост начинается там, где действие становится привычкой.',
    price: 395000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/34a704fc-c93c-4fb7-a3f4-fd85ee5217a3.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: '',
    fit: 'Unisex',
    is_new: true,
    is_limited: true,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-04',
  },
  {
    id: '5d7208be-638a-4431-98d5-40b599436ef9',
    name: 'Свеча "Click"',
    slug: 'svecha-click',
    description: '',
    price: 90000,
    category_id: 'aksessuary',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/48cace4f-a740-4c84-a615-e475b1f610fe.webp',
    ],
    sizes: [],
    colors: [],
    material: '',
    fit: '',
    is_new: true,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-05',
  },
  {
    id: '9f6ab113-dccd-4880-9c07-12683602c1b2',
    name: 'Ушанка + варежки на шнурке',
    slug: 'ushanka-varezhki-na-shnurke',
    description: 'Мягкий эко-мех и тёплый уютный подклад. Зимний комплект для города, гор, поездок за город и apres-ski настроения. Варежки со съёмным шнурком — удобно и эстетично. Их можно носить на шее или использовать как стильные кармашки. Цвета — чёрный и серый. Комплект упакован в красивый синий пыльник — идеально для хранения. Тепло. Эстетика. Winter Dream.',
    price: 500000,
    category_id: 'golovnye-ubory',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/57592540-b15a-4b7b-83eb-a348ac7b379b.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/56630702-0a89-4028-9356-ede50e93768f.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/83d22a84-756b-4488-9d81-dd4cdb59144d.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/824457a9-26e2-4554-9737-c4b421aa68f7.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/95fb19cb-3bff-4125-8b2f-afeb6f336c68.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/5fbbf61d-7492-48e2-8c52-f20c2441a9e5.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/0bf8820d-b9a6-473d-bea0-5de4940123cb.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/1ce1cfb9-7642-4333-98d7-58bb355e28c0.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Эко-мех',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-06',
  },
  {
    id: 'a3afbfbb-3688-4894-af2d-6b418efa9544',
    name: 'Кепка Click Travel, Арка',
    slug: 'kepka-click-travel-arka',
    description: 'Лёгкая кепка в стиле унисекс из прочного хлопка. Идеальна для города, путешествий и фестивалей. Лаконичный принт и комфортная посадка — всё, что нужно для настроения "в потоке". Материал: 100% хлопок. Размер: регулируемый.',
    price: 53900,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591352-707802.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591353-650435.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591354-683123.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591355-907982.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591356-775635.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591357-382652.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591358-692039.webp',
    ],
    sizes: [],
    colors: [],
    material: '100% хлопок',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-07',
  },
  {
    id: '31b23f02-41e5-46f9-b879-d9a306558252',
    name: 'Кепка Click Travel, Память',
    slug: 'kepka-click-travel-pamyat',
    description: 'Лёгкая кепка в стиле унисекс из прочного хлопка. Идеальна для города, путешествий и фестивалей. Лаконичный принт и комфортная посадка — всё, что нужно для настроения "в потоке". Материал: 100% хлопок. Размер: регулируемый.',
    price: 53900,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591346-134492.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591347-898967.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591348-668315.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591349-347991.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591350-150509.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591351-700329.webp',
    ],
    sizes: [],
    colors: [],
    material: '100% хлопок',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-08',
  },
  {
    id: '7d3cd873-96fd-4ed8-bd04-fa0518ed168c',
    name: 'Футболка "Close Friends x Click"',
    slug: 'futbolka-close-friends-x-click',
    description: 'Футболка "Close Friends x Click" создана для тех, кто ценит комфорт, минимализм и универсальность. Выполненная из 82% натурального хлопка, она гарантирует мягкость и воздухопроницаемость, идеально подходя для повседневной носки. Глубокий чёрный цвет и лаконичный дизайн делают её отличным выбором для любого образа — от расслабленного до более формального. Носите её с джинсами, брюками или юбкой, чтобы выразить свою индивидуальность и выделиться в любой компании. Создана для настоящих "близких друзей" и тех, кто не боится делать решительные "клики" в жизни!',
    price: 200000,
    category_id: 'kollaboratsii',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591361-800351.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591362-858928.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591363-474922.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591364-242205.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591365-339315.webp',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [],
    material: '82% хлопок',
    fit: 'Unisex',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-09',
  },
  {
    id: 'e34e49c2-e155-41c8-8581-66e8ab83f59d',
    name: 'Свитшот "Рост"',
    slug: 'svitshot-rost',
    description: 'Рост. Свитшот о действии. Когда один шаг повторяется — он становится движением. Яркий зелёный — энергия роста и перемен. Принт — про силу, которая появляется, когда мы действуем вместе. Послание: Рост начинается там, где действие становится привычкой.',
    price: 570000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/540d1879-a42f-4ae2-854d-5be0e90daedc.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/355c29e0-1151-40c4-9fd1-e54c4b896ec1.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/748d0050-7b38-464f-a58b-c9c3e422cd1d.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: '',
    fit: 'Unisex',
    is_new: false,
    is_limited: true,
    is_bestseller: true,
    stock: 50,
    created_at: '2024-06-10',
  },
  {
    id: '0d7ae100-86f0-4d0c-b5ac-cb57f5599e02',
    name: 'Картхолдер',
    slug: 'kartkholder',
    description: 'Картхолдеры от Click Brandshop — это сочетание функциональности, надежности и минималистичного стиля. Идеальное решение для тех, кто ценит порядок, мобильность и безопасность своих карт. Компактный и стильный — легко помещается в любой карман или сумку. Вмещает несколько банковских карт, визиток и даже мелкие купюры. Надежная конструкция защищает карты от размагничивания и повреждений. Доступен в четырёх стильных вариантах: Чёрный, Синий, Красный, Чёрный узор.',
    price: 32000,
    category_id: 'aksessuary',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/9dbdbbc7-aff1-4ead-97dc-5d9eac261234.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/6680f0fd-6a1f-4fc2-ad69-17ea0f680b08.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/e03ced69-dc3c-4bc6-9db7-8ce867f2d730.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/03128a01-ede4-4baa-b461-ade66f19fee1.webp',
    ],
    sizes: [],
    colors: [],
    material: '',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-11',
  },
  {
    id: '5c8b5614-d574-4db1-946b-ad950a898a0c',
    name: 'Панама Click Travel, Арка',
    slug: 'panama-click-travel-arka',
    description: 'Zamonaviy panama — quyoshdan himoya va uslubli ko\'rinish. Shaharda ham, tabiatda ham do\'stona ko\'rinish beradi. Material: zich paxta. O\'lcham: universal.',
    price: 119000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591340-887516.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591341-300414.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591342-979464.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591343-892502.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591344-258111.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Хлопок',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-12',
  },
  {
    id: '7fd0b4b5-1100-4f97-b5b4-d41d6df498bf',
    name: 'Свитшот "Путь"',
    slug: 'svitshot-put-1',
    description: 'Рост. Свитшот о действии. Когда один шаг повторяется — он становится движением. Яркий зелёный — энергия роста и перемен. Принт — про силу, которая появляется, когда мы действуем вместе. Послание: Рост начинается там, где действие становится привычкой.',
    price: 570000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/0197838e-764b-4efb-b53c-a9592f8208c7.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/49a3194f-f2e0-4ecc-97e6-6c3366413b8a.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: '',
    fit: 'Unisex',
    is_new: false,
    is_limited: true,
    is_bestseller: true,
    stock: 50,
    created_at: '2024-06-13',
  },
  {
    id: '3b41f303-40c4-4dd6-a7ea-9ddf45bd20e7',
    name: 'Панама Click Travel, Память',
    slug: 'panama-click-travel-pamyat',
    description: 'Zamonaviy panama — quyoshdan himoya va uslubli ko\'rinish. Shaharda ham, tabiatda ham do\'stona ko\'rinish beradi. Material: zich paxta. O\'lcham: universal.',
    price: 119000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591332-317697.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591333-901657.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591334-303390.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591335-777957.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591336-491116.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591337-435080.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Хлопок',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-14',
  },
  {
    id: '72f1d7a1-f805-45b5-a15e-c0f5f52d8924',
    name: 'Свитшот "Путь"',
    slug: 'svitshot-put-2',
    description: 'Путь. Свитшот о действии. Когда один шаг повторяется — он становится движением. Принт — про силу, которая появляется, когда мы действуем вместе.',
    price: 570000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/a46f6e53-253b-402d-aee1-095688cdba83.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/c10c7813-dad9-42ac-8f4c-ed4ca865ef44.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/3febb4ce-104c-44f9-92a7-c8c4acf0a01f.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/69b195de-675d-47b9-99c3-1413edf17d3f.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: '',
    fit: 'Unisex',
    is_new: false,
    is_limited: true,
    is_bestseller: true,
    stock: 50,
    created_at: '2024-06-15',
  },
  {
    id: '58f623c3-84a6-42e3-ab6f-2296d30cd01c',
    name: 'Футболка Sublimation x Click',
    slug: 'futbolka-sublimation-x-click',
    description: 'Футболка "Sublimation x Click" создана для тех, кто ценит комфорт, минимализм и универсальность. Выполненная из 82% натурального хлопка, она гарантирует мягкость и воздухопроницаемость, идеально подходя для повседневной носки. Глубокий чёрный цвет и лаконичный дизайн делают её отличным выбором для любого образа — от расслабленного до более формального. Создана для настоящих "близких друзей" и тех, кто не боится делать решительные "клики" в жизни!',
    price: 200000,
    category_id: 'kollaboratsii',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/608902-866032.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/608903-388412.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/608904-706153.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/608905-197030.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/608906-934290.webp',
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [],
    material: '82% хлопок',
    fit: 'Unisex',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-16',
  },
  {
    id: '6aedae44-4309-41d9-88b9-14b462f8e037',
    name: 'Худи «Задыхаюсь»',
    slug: 'khudi-zadykhayus',
    description: 'Цвет: Тёмно-серый. Коллекция: Воздух, в котором мы дышим. Город, ставший фильтром для собственного смога. Фигура в ярком узбекском икате и противогазе — символ современного человека, застрявшего между культурой и техногенной реальностью. Атмосфера тревоги, одиночества и загрязнённого будущего. Арт-принт Kuznetsovs Gallery. Унисекс, свободный крой. 100% хлопок. QR-код: click for oxygen. Не просто худи. Это дыхание на ткани.',
    price: 670000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/c19e7e45-4df1-45f3-a9cc-24d2ee813327.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/8df58e58-f24f-433b-a307-6201ab6484c3.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: '100% хлопок',
    fit: 'Unisex',
    is_new: false,
    is_limited: true,
    is_bestseller: true,
    stock: 50,
    created_at: '2024-06-17',
  },
  {
    id: '96ad645d-bad3-491d-9175-ca2550d5f912',
    name: 'Бананка Click Travel, Арка',
    slug: 'bananka-click-travel-arka',
    description: 'Компактная сумка на пояс, которая вмещает всё необходимое. Можно носить через плечо или на поясе. Простой стиль — максимум свободы. Материал: водоотталкивающий нейлон.',
    price: 149000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595318-283672.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595319-254393.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595320-364146.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595321-994301.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595322-759974.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595323-303823.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Водоотталкивающий нейлон',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-18',
  },
  {
    id: '443680a5-dfa6-4449-9a31-b1e6f67a2120',
    name: 'Бананка Click Travel, Память',
    slug: 'bananka-click-travel-pamyat',
    description: 'Компактная сумка на пояс, которая вмещает всё необходимое. Можно носить через плечо или на поясе. Простой стиль — максимум свободы. Материал: водоотталкивающий нейлон.',
    price: 149000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595299-376870.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595300-903884.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595301-803075.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595302-315743.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/595303-439736.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Водоотталкивающий нейлон',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-19',
  },
  {
    id: 'db8a79cb-b24d-4353-bacb-9d0dfb31cfc0',
    name: 'Свитшот «Молчание империи»',
    slug: 'svitshot-molchanie-imperii',
    description: 'Цвет: Шоколад. Коллекция: Воздух, в котором мы дышим. Памятник Амиру Темуру в маске. Великий полководец, превращённый в символ тревоги. Этот принт — провокационный и честный: он показывает, что даже самые прочные образы истории теряют силу, если в настоящем — нечем дышать. Маска на лице памятника говорит за весь город. Арт-принт: памятник Амиру Темуру в Ташкенте. Авторская интерпретация от Kuznetsovs Gallery. Унисекс фасон, свободная посадка. Плотный хлопковый трикотаж. QR-код на спине — click for oxygen и переход к Yashil Meros. История не вечна, если нет воздуха будущего.',
    price: 570000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/9872aa2e-e5d5-4fc3-b7f0-5202c9a159cc.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/75f9f650-4c2f-4815-bca7-efaec5eede3b.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/a1fe6b1f-0eec-40d1-bd1e-4d6d19458963.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/b982ddb0-7025-451d-ae0d-47933e2b20bb.webp',
    ],
    sizes: ['S-M', 'L-XL', 'XXL'],
    colors: [],
    material: 'Хлопковый трикотаж',
    fit: 'Unisex',
    is_new: false,
    is_limited: true,
    is_bestseller: true,
    stock: 50,
    created_at: '2024-06-20',
  },
  {
    id: '30d64441-6f10-45e7-a810-b7884b54b576',
    name: 'Шоппер Click Travel, Арка',
    slug: 'shopper-click-travel-arka',
    description: 'Эко-шоппер для повседневных задач. Вместительный, стильный и прочный — незаменимый аксессуар для покупок или офиса. Материал: 100% хлопок. Размер: 38x42 см.',
    price: 99000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591315-749205.webp',
    ],
    sizes: [],
    colors: [],
    material: '100% хлопок',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-21',
  },
  {
    id: '7e006da4-4301-44dc-b22c-f36d2eca8c4b',
    name: 'Худи «Молчание империи»',
    slug: 'khudi-molchanie-imperii',
    description: 'Цвет: Шоколад. Коллекция: Воздух, в котором мы дышим. Памятник Амиру Темуру в маске. Великий полководец, превращённый в символ тревоги. Этот принт — провокационный и честный: он показывает, что даже самые прочные образы истории теряют силу, если в настоящем — нечем дышать. Маска на лице памятника говорит за весь город. Арт-принт: памятник Амиру Темуру в Ташкенте. Авторская интерпретация от Kuznetsovs Gallery. Унисекс фасон, свободная посадка. Плотный хлопковый трикотаж. QR-код на спине — click for oxygen и переход к Yashil Meros. История не вечна, если нет воздуха будущего.',
    price: 670000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/92653c67-774e-4d81-8d13-2a11fec88d56.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: 'Хлопковый трикотаж',
    fit: 'Unisex',
    is_new: false,
    is_limited: true,
    is_bestseller: true,
    stock: 50,
    created_at: '2024-06-22',
  },
  {
    id: '85d07018-9d8c-4724-9fe4-e09d89bad6ec',
    name: 'Футболка «Молчание империи»',
    slug: 'futbolka-molchanie-imperii',
    description: 'Цвет: Шоколад. Коллекция: Воздух, в котором мы дышим. Памятник Амиру Темуру в маске. Великий полководец, превращённый в символ тревоги. Этот принт — провокационный и честный: он показывает, что даже самые прочные образы истории теряют силу, если в настоящем — нечем дышать. Маска на лице памятника говорит за весь город. Арт-принт: памятник Амиру Темуру в Ташкенте. Авторская интерпретация от Kuznetsovs Gallery. Унисекс, свободный крой. 100% хлопок. QR-код: click for oxygen.',
    price: 395000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/95114ea6-88bc-4cdc-9085-4aeff3b316bb.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: '100% хлопок',
    fit: 'Unisex',
    is_new: false,
    is_limited: true,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-23',
  },
  {
    id: 'b6d5678c-1954-4a98-a142-3afde9f5ad27',
    name: 'Шоппер Click Travel, Память',
    slug: 'shopper-click-travel-pamyat',
    description: 'Эко-шоппер для повседневных задач. Вместительный, стильный и прочный — незаменимый аксессуар для покупок или офиса. Материал: 100% хлопок. Размер: 38x42 см.',
    price: 99000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591308-950725.webp',
    ],
    sizes: [],
    colors: [],
    material: '100% хлопок',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-24',
  },
  {
    id: '0beffd76-90b3-49e4-8fa0-203186288fb6',
    name: 'Футболка «Задыхаюсь»',
    slug: 'futbolka-zadykhayus',
    description: 'Цвет: Тёмно-серый. Коллекция: Воздух, в котором мы дышим. Город, ставший фильтром для собственного смога. Фигура в ярком узбекском икате и противогазе — символ современного человека, застрявшего между культурой и техногенной реальностью. Атмосфера тревоги, одиночества и загрязнённого будущего. Арт-принт Kuznetsovs Gallery. Унисекс, свободный крой. 100% хлопок. QR-код: click for oxygen. Не просто футболка. Это дыхание на ткани.',
    price: 395000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/3f2d4024-60d7-4ff7-a5db-0bdc28e24072.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/6c05b862-9ef8-4601-859a-43d238d6e61f.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: '100% хлопок',
    fit: 'Unisex',
    is_new: false,
    is_limited: true,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-25',
  },
  {
    id: 'fce1512a-f7c4-43d7-ac09-b340b6e5bf86',
    name: 'Рюкзак Click Travel, Арка',
    slug: 'ryukzak-click-travel-arka',
    description: 'Минималистичный рюкзак с удобными лямками, большим отделением и отделом для ноутбука. Лёгкий, но вместительный — надёжный спутник в городе. Материал: нейлон. Объём: 20-25 л.',
    price: 339000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591301-141367.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591302-225704.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591303-221688.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591304-289883.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Нейлон',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-26',
  },
  {
    id: '69dc6bf3-83ac-4bdb-8e26-418c8caea86f',
    name: 'Рюкзак Click Travel, Память',
    slug: 'ryukzak-click-travel-pamyat',
    description: 'Минималистичный рюкзак с удобными лямками, большим отделением и отделом для ноутбука. Лёгкий, но вместительный — надёжный спутник в городе. Материал: нейлон. Объём: 20-25 л.',
    price: 339000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591294-722516.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591295-180757.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591296-345246.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591297-838317.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591298-337274.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Нейлон',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-27',
  },
  {
    id: 'f7017412-1cd2-4c1c-9d16-c7db1fb54df4',
    name: 'Футболка «Облако жадности»',
    slug: 'futbolka-oblako-zhadnosti',
    description: 'Цвет: Светло-серый. Коллекция: Воздух, в котором мы дышим. Когда воздух превращают в валюту — теряется сама ценность жизни. Принт с черным облаком и национальными орнаментами в виде знаков валют — метафора того, как жадность и безразличие ведут к экологическим катастрофам. Маленькая фигура человека внизу — мы с вами, перед лицом разрушений. Принт от Kuznetsovs Gallery. Унисекс фасон. Натуральный дышащий хлопок. QR-код сзади ведёт к экологической инициативе Yashil Meros.',
    price: 395000,
    category_id: 'yashil-meros',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/fdae2bf0-2227-409e-bdb0-8b95ec9aba52.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/a94ce369-38a8-4996-8887-9706364bd23c.webp',
    ],
    sizes: ['S-M', 'L-XL'],
    colors: [],
    material: 'Хлопок',
    fit: 'Unisex',
    is_new: false,
    is_limited: true,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-28',
  },
  {
    id: '693ef7eb-e9c9-43b0-a1f2-7a28c8cd347d',
    name: 'Бутылка Click Travel, Память',
    slug: 'butylka-click-travel-pamyat',
    description: 'Многоразовая бутылка для воды с минималистичным дизайном. Удобно брать с собой на тренировку, прогулку или в офис. Объём: 500 мл. Материал: Soft touch.',
    price: 149000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591288-669734.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591289-261696.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591285-168515.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591286-317544.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591287-922044.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Soft touch',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-29',
  },
  {
    id: 'a8381012-7bbe-48d0-af5f-5ed6e370d463',
    name: 'Бутылка Click Travel, Арка',
    slug: 'butylka-click-travel-arka',
    description: 'Многоразовая бутылка для воды с минималистичным дизайном. Удобно брать с собой на тренировку, прогулку или в офис. Объём: 500 мл. Материал: Soft touch.',
    price: 149000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591290-657885.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591291-593125.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591292-905723.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591293-415825.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Soft touch',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-06-30',
  },
  {
    id: 'edba4fb9-97c8-46b4-b0cc-f9f6e5c082aa',
    name: 'Подушка дорожная Click Travel, Арка',
    slug: 'podushka-dorozhnaya-click-travel-arka',
    description: 'Мягкая подушка для сна в дороге. Повторяет форму шеи, обеспечивая комфорт даже в самых долгих поездках. Материал: хлопок + наполнитель memory foam. Размер: универсальный.',
    price: 179000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591273-302280.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591274-317191.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591275-953923.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591276-634781.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591277-483162.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/591278-651724.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Хлопок + memory foam',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-07-01',
  },
  {
    id: '0193f75c-271f-4f5c-a56a-b783a431833b',
    name: 'Подушка дорожная Click Travel, Память',
    slug: 'podushka-dorozhnaya-click-travel-pamyat',
    description: 'Мягкая подушка для сна в дороге. Повторяет форму шеи, обеспечивая комфорт даже в самых долгих поездках. Материал: хлопок + наполнитель memory foam. Размер: универсальный.',
    price: 179000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599713-406038.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599714-951801.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599715-411819.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599716-191160.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599717-252340.webp',
    ],
    sizes: [],
    colors: [],
    material: 'Хлопок + memory foam',
    fit: '',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-07-02',
  },
  {
    id: '92c6bbfc-3706-4516-99a7-530019b6580a',
    name: 'Поло Click Travel, Память',
    slug: 'polo-click-travel-pamyat',
    description: 'Классическая футболка-поло из трикотажа пике. Универсальный стиль с лёгким акцентом — подходит и для офиса, и для прогулки. Материал: хлопок/эластан. Размеры: S, M, L, XL, XXL.',
    price: 189000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599728-448493.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599729-300909.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599730-781901.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599731-414142.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599732-212842.webp',
    ],
    sizes: ['S / 46', 'M / 48', 'L / 50', 'XL / 52', 'XXL / 54'],
    colors: [],
    material: 'Хлопок/эластан',
    fit: 'Unisex',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-07-03',
  },
  {
    id: '9f24acd1-97d1-4063-953d-0f4571bf718f',
    name: 'Поло Click Travel, Арка',
    slug: 'polo-click-travel-arka',
    description: 'Классическая футболка-поло из трикотажа пике. Универсальный стиль с лёгким акцентом — подходит и для офиса, и для прогулки. Материал: хлопок/эластан. Размеры: S, M, L, XL, XXL.',
    price: 189000,
    category_id: 'click-travel',
    images: [
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599723-471496.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599724-984581.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599725-128890.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599726-242112.webp',
      'https://robosell.ams3.digitaloceanspaces.com/robosell/product/599727-189887.webp',
    ],
    sizes: ['S / 46', 'M / 48', 'L / 50', 'XL / 52', 'XXL / 54'],
    colors: [],
    material: 'Хлопок/эластан',
    fit: 'Unisex',
    is_new: false,
    is_limited: false,
    is_bestseller: false,
    stock: 50,
    created_at: '2024-07-04',
  },
];
